### ISSUE TITLE
3 errors after following all instructs 

### ISSUE THREAD

**Issue by Tyylr** [DevToaster/kryst4lmeth_opensource#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'SourceEngine::Vector2D'	kryst4lmeth	C:\Users\USER\Desktop\kmeth\kryst4lmeth_opensource-master\kryst4lmeth\Menu.cpp	502	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'SourceEngine::Vector2D'	kryst4lmeth	C:\Users\USER\Desktop\kmeth\kryst4lmeth_opensource-master\kryst4lmeth\Menu.cpp	502	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'SourceEngine::Vector2D'	kryst4lmeth	C:\Users\USER\Desktop\kmeth\kryst4lmeth_opensource-master\kryst4lmeth\Menu.cpp	502

**Comment by DevToaster** [comment]
My bad, should be fixed now

**Comment by Tyylr** [comment]
thank you
